server:
    port: 8084
spring:
    application:
        name: sleuth

    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/zipkin
        username: root
        password: 123456
        # Switch this on to create the schema on startup:
#        initialize: true
#        continueOnError: true
    sleuth:
        enabled: false
zipkin:
    storage:
        type: mysql

eureka:
    instance:
        prefer-ip-address: true
        appname: ${spring.application.name}
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

    client:
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/
